plot3<-function()
{
  cat("\nPlease enter the filepath:\n\n")
  filepath<-readline()
  wd<-gsub("\\\\","/",filepath)
  setwd(wd)
  cat("\nPlease enter the filename with extension:\n\n")
  filename<-readline()
  full_data<-read.table(filename,stringsAsFactors = FALSE,sep = ";",header = TRUE)
  full_data$Date<-as.Date(full_data$Date,"%d/%m/%Y")
  req_data<-subset(full_data,full_data$Date<='2007-02-02')
  req_data<-subset(req_data,req_data$Date>='2007-02-01')
  req_data$Date_time<-as.POSIXlt(paste(req_data$Date,req_data$Time))
  req_data$Sub_metering_1<-as.numeric(req_data$Sub_metering_1)
  req_data$Sub_metering_2<-as.numeric(req_data$Sub_metering_2)
  req_data$Sub_metering_3<-as.numeric(req_data$Sub_metering_3)
  png(filename = "plot3.png")
  plot(req_data$Date_time,req_data$Sub_metering_1,xlab="",ylab="Energy Sub Metering",type="l")
  lines(req_data$Date_time,req_data$Sub_metering_2,col="red")
  lines(req_data$Date_time,req_data$Sub_metering_3,col="blue")
  legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1),col=c("black","red","blue"))
  dev.off()
  plot(req_data$Date_time,req_data$Sub_metering_1,xlab="",ylab="Energy Sub Metering",type="l")
  lines(req_data$Date_time,req_data$Sub_metering_2,col="red")
  lines(req_data$Date_time,req_data$Sub_metering_3,col="blue")
  legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1),col=c("black","red","blue"))
  cat("\nThe plot has been saved as plot3.png in the entered filepath")
}