plot2<-function()
{
  cat("\nPlease enter the filepath:\n\n")
  filepath<-readline()
  wd<-gsub("\\\\","/",filepath)
  setwd(wd)
  cat("\nPlease enter the filename with extension:\n\n")
  filename<-readline()
  full_data<-read.table(filename,stringsAsFactors = FALSE,sep = ";",header = TRUE)
  full_data$Date<-as.Date(full_data$Date,"%d/%m/%Y")
  req_data<-subset(full_data,full_data$Date<='2007-02-02')
  req_data<-subset(req_data,req_data$Date>='2007-02-01')
  req_data$Date_time<-as.POSIXlt(paste(req_data$Date,req_data$Time))
  req_data$Global_active_power<-as.numeric(req_data$Global_active_power)
  png(filename = "plot2.png")
  plot(req_data$Date_time,req_data$Global_active_power,xlab="",ylab="Global Active Power (kilowatts)",type="l")
  dev.off()
  plot(req_data$Date_time,req_data$Global_active_power,xlab="",ylab="Global Active Power (kilowatts)",type="l")
  cat("\nThe plot has been saved as plot2.png in the entered filepath")
}