plot4<-function()
{
  cat("\nPlease enter the filepath:\n\n")
  filepath<-readline()
  wd<-gsub("\\\\","/",filepath)
  setwd(wd)
  cat("\nPlease enter the filename with extension:\n\n")
  filename<-readline()
  full_data<-read.table(filename,stringsAsFactors = FALSE,sep = ";",header = TRUE)
  full_data$Date<-as.Date(full_data$Date,"%d/%m/%Y")
  req_data<-subset(full_data,full_data$Date<='2007-02-02')
  req_data<-subset(req_data,req_data$Date>='2007-02-01')
  req_data$Date_time<-as.POSIXlt(paste(req_data$Date,req_data$Time))
  req_data$Global_active_power<-as.numeric(req_data$Global_active_power)
  req_data$Global_active_power<-as.numeric(req_data$Global_reactive_power)
  req_data$Sub_metering_1<-as.numeric(req_data$Sub_metering_1)
  req_data$Sub_metering_2<-as.numeric(req_data$Sub_metering_2)
  req_data$Sub_metering_3<-as.numeric(req_data$Sub_metering_3)
  req_data$Voltage<-as.numeric(req_data$Voltage)
  png(filename = "plot4.png")
  par(mfrow=c(2,2))
  par(mar=c(2,4,2,2))
  plot(req_data$Date_time,req_data$Global_active_power,xlab="",ylab="Global Active Power (kilowatts)",type="l")
  plot(req_data$Date_time,req_data$Voltage,xlab="datetime",ylab="Voltage",type="l")
  plot(req_data$Date_time,req_data$Sub_metering_1,xlab="",ylab="Energy Sub Metering",type="l")
  lines(req_data$Date_time,req_data$Sub_metering_2,col="red")
  lines(req_data$Date_time,req_data$Sub_metering_3,col="blue")
  legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1),col=c("black","red","blue"))
  plot(req_data$Date_time,req_data$Global_reactive_power,xlab="datetime",ylab="Global_reactive_power",type="l")
  dev.off()
  par(mfrow=c(2,2))
  par(mar=c(2,4,2,2))
  plot(req_data$Date_time,req_data$Global_active_power,xlab="",ylab="Global Active Power (kilowatts)",type="l")
  plot(req_data$Date_time,req_data$Voltage,xlab="datetime",ylab="Voltage",type="l")
  plot(req_data$Date_time,req_data$Sub_metering_1,xlab="",ylab="Energy Sub Metering",type="l")
  lines(req_data$Date_time,req_data$Sub_metering_2,col="red")
  lines(req_data$Date_time,req_data$Sub_metering_3,col="blue")
  legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1),col=c("black","red","blue"))
  plot(req_data$Date_time,req_data$Global_reactive_power,xlab="datetime",ylab="Global_reactive_power",type="l")
  cat("\nThe plot has been saved as plot4.png in the entered filepath")
}